### ISSUE TITLE
Create howto for how to use the project

### ISSUE THREAD

**Issue by seetee** [tcstenungsund/bord__dokumentation#5]
Create step-by-step instructions for common use cases. 

- [x] How to create a new theme
- [x] How to add the project and a specifik theme to a new device 
- [ ] How to create new animated SVGs

**Comment by pontalainen** [comment]
I have some thoughts and suggestions when it comes to "_How to create a new theme_" and "_How to add the project and a specifik theme to a new device_".

First how to create a new theme, which basically means how to set the project up for a new customer, which basically also is the second question, so I´m going to answer both at the same time. Boom, mic drop!

*Picks up the mic again*

So... Basically each customer themes is going to be located in a unique to them GitHub repository. The name of each repository should also be the name of that specific theme, which in my opinion should be the name of the customer, i.e. Molekylverkstan. This is what the name of their table in the database will be.

In this repository, the customer will be able to add/edit/remove their own markdown files as they please (using our standard, of course). I´m not really concerned about what they write in their file, as long as it´s clean markdown (we´ll come back to details for the standard later).
Each file is going to be a page they would like the consumer to be able to see. If the product they offer isn´t really page-based (like Project Fruit for example), then they can at least think about each markdown file as being connected to a unique NFC-card. That would in the case of Fruit mean apples has their own file(/page) bananas have their own, oranges... and so on and so on. I highly suggest each repository has a home page file, and "_start.md_" is a great one.

The names of these files should be the names of what they want to display. If they want to display a page about Borealis, then the file name should be borealis. It doesn´t really matter what it is, but it is easier to manage later on, since each NFC-card is going to be connected to a certain page, and being able to kind of know which page is which based only on the names does make sense, to me at least. I also suggest these file names are all lowercase. Not that it makes a huge difference, but it should be good practice.

Good to know for those non-technical customers is that all files need to have a file ending of "_.md_". That means the page for Borealis in the Molekylverkstan repository would have a file name of "_borealis.md_".

For the "adding the project to a new device", this basically means to download the PWA in a browser, and setting the customer up with their own password/key/whatever we use (we havn´t implemented that at the time of writing this). The PWA will be the same for all customers, and the login is what keeps the different themes separated. After login, the customer should be taken to their theme´s home page (_start.md_).

How the NFC-cards I have no idea, but that needs to be considered soon.

**Comment by pontalainen** [comment]
Sooo... there´s been some changes. Basically, nothing in the earlier comment is up-to-date. Since the migration to Laravel a lot of problems have disappeared and so has the solutions to some of those problems. Here´s how a new customer set´s the project up:

First, they head to the website, let´s say _www.learnol.com_. There they will be redirected to _/register_, where they will have to register a new admin account. When done they will be redirected to the home page; _/bord_. Here they will be able to see all of their pages, once they have some. When that time comes, they will be able to see each page individually by clicking on them. The pages will also have **edit** as well as **delete** buttons, used for just that; editing and deleting the chosen page.

To get started creating pages they click on **New Page**. They will be directed to _/create_. Here they will be presented with three inputs; name, content, a markdown switch and an image input. The name is basically the name and title for the page. The content is the main bit of text or HTML on the new page, and by using the switch they can toggle whether they want to write the content in markdown or just plain text. If they choose markdown, then the text they input will be automatically converted to and stored as HTML. This means access to things like lists, headers and so on. The image chosen can be whatever the like, but it should be noted that an abnormal aspect ratio might look wierd on the final page.

To connect NFC cards to the pages, they can from the home page click on **Edit Cards**, where they can choose which cards to connect to what page.

When finished with all the inputs they´ll click on **submit**, which will save the page and redirect them back to the home page. We recommend that the first page they create is what will be the start page for the non-admin users later on. This start page should be named Start, and the content and image can be whatever they like.

To create non-admin accounts, they will from the home page click on their name, which will drop down a menu with one of the options being **create user**. When having clicked on said button, they will be presented with what looks very much like the _register_-page, with the exception being the lack of an _email_ input. This account will later be logged into whenever they want to put their product in production, open for other customers.

When the regular user has been created, they will automatically be redirected to the start page they created earlier. From here they can either scan an NFC card, or log out to then log in as the admin, to then add or edit pages.

**Comment by pontalainen** [comment]
We don´t have SVG animation covered, but we don´t knwo how to do it ourselves sooo...
